# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool: satishpool

stages:
  - stage: buildproject
    displayName: Build Project
    jobs:
      - job: buildproject
        steps:
         - task: CmdLine@2
           inputs:
             script: 'mvn clean package'
         - task: CopyFiles@2
           inputs:
             SourceFolder: '$(System.DefaultWorkingDirectory)/target/'
             Contents: '*'
             TargetFolder: 'C:\apache-tomcat-9.0.93\webapps'
         - task: CmdLine@2
           inputs:
             script: |
               cd C:\apache-tomcat-9.0.93\bin
               shutdown.bat
               start.bat
